version: '3'

services:
  db:
    image: postgres
  web:
    build: ./coffee_cart
    volumes:
      - ./coffee_cart:/app/coffee_cart
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  # nginx:
  #   build: ./nginx
  #   command: nginx
  #   volumes:
  #     - ./nginx/static:/usr/share/nginx/html
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "5000:80"