# Generated by Django 2.2 on 2019-04-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
